Add readme.md

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -1,8 +1,3 @@
-# EXAMPLE USAGE:
-#
-#   Refer for explanation to following link:
-#   https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md
-#
 pre-push:
   parallel: false
   commands:
@@ -15,12 +10,24 @@ pre-push:
           exit 1
         fi
 
+    ensure-clean-working-directory:
+      run: |
+        if ! git diff --quiet || ! git diff --cached --quiet; then
+          echo "Error: O diretório de trabalho não está limpo. Por favor, faça commit ou stash das alterações."
+          exit 1
+        fi
+
     update-develop:
       run: |
         if ! git rev-parse --verify develop >/dev/null 2>&1; then
-          echo "A branch 'develop' não existe. Criando a branch 'develop'..."
+          echo "A branch 'develop' não existe localmente. Criando a branch 'develop'..."
           if ! git checkout -b develop; then
-            echo "Error: Não foi possível criar a branch 'develop'."
+            echo "Error: Não foi possível criar a branch 'develop' localmente."
+            exit 1
+          fi
+
+          if ! git push --set-upstream origin develop; then
+            echo "Error: Não foi possível criar a branch 'develop' no repositório remoto."
             exit 1
           fi
         else
@@ -30,24 +37,42 @@ pre-push:
           fi
         fi
 
-        if ! git pull origin develop; then
-          echo "Error: Não foi possível atualizar a branch 'develop' com a remota."
-          exit 1
+        if git ls-remote --heads origin develop | grep develop >/dev/null 2>&1; then
+          if ! git pull origin develop --rebase; then
+            echo "Error: Não foi possível atualizar a branch 'develop' com a remota."
+            exit 1
+          fi
+        else
+          echo "A branch 'develop' não existe no repositório remoto. Pulando o pull."
         fi
 
-    merge-develop:
+    rebase-current-branch:
       run: |
-        if ! git checkout $current_branch; then
-          echo "Error: Não foi possível voltar para a branch atual '${current_branch}'."
-          exit 1
+        current_branch=$(git rev-parse --abbrev-ref HEAD)
+        if [ "$current_branch" != "develop" ]; then
+          if ! git rebase develop; then
+            echo "Error: O rebase da branch 'develop' na branch '${current_branch}' falhou. Por favor, resolva os conflitos de merge e continue o rebase."
+            exit 1
+          fi
+        else
+          echo "A branch atual está em 'develop'. Pulando rebase."
         fi
 
-        if ! git merge --no-ff --no-edit develop; then
-          echo "Error: Não foi possível realizar o merge da branch 'develop' na branch '${current_branch}'."
-          exit 1
+    push-current-branch:
+      run: |
+        current_branch=$(git rev-parse --abbrev-ref HEAD)
+        if ! git rev-parse --abbrev-ref --symbolic-full-name @{u} >/dev/null 2>&1; then
+          echo "A branch '${current_branch}' não tem um upstream configurado. Configurando upstream..."
+          if ! git push --set-upstream origin $current_branch; then
+            echo "Error: Não foi possível fazer push da branch '${current_branch}' para o repositório remoto."
+            exit 1
+          fi
+        else
+          if ! git push; then
+            echo "Error: Não foi possível fazer push da branch '${current_branch}' para o repositório remoto."
+            exit 1
+          fi
         fi
-
-
 
 pre-commit:
   parallel: true
