Add readme.md

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -61,17 +61,13 @@ pre-push:
     push-current-branch:
       run: |
         current_branch=$(git rev-parse --abbrev-ref HEAD)
-        if ! git rev-parse --verify origin/$current_branch >/dev/null 2>&1; then
-          echo "A branch '$current_branch' não existe no repositório remoto. Criando a branch '$current_branch'..."
-          if ! git push --set-upstream origin $current_branch; then
-            echo "Error: Não foi possível criar a branch '$current_branch' no repositório remoto."
+        if [ "$current_branch" != "develop" ]; then
+          if ! git push origin "$current_branch"; then
+            echo "Error: O push da branch '${current_branch}' falhou."
             exit 1
           fi
         else
-          if ! git push; then
-            echo "Error: Não foi possível fazer push da branch '$current_branch' para o repositório remoto."
-            exit 1
-          fi
+          echo "A branch atual está em 'develop'. Pulando push."
         fi
 
 
