Add readme.md

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -31,7 +31,7 @@ pre-push:
             exit 1
           fi
 
-          # Tenta fazer push da branch develop para o repositório remoto e configurar o upstream
+          # Tenta fazer push da branch develop para o repositório remoto
           if ! git push --set-upstream origin develop; then
             echo "Error: Não foi possível criar a branch 'develop' no repositório remoto."
             exit 1
@@ -41,12 +41,16 @@ pre-push:
             echo "Error: Não foi possível fazer checkout na branch 'develop'."
             exit 1
           fi
+        fi
 
-          # Puxa as últimas alterações da branch develop
+        # Verifica se a branch 'develop' existe no repositório remoto antes de fazer pull
+        if git ls-remote --heads origin develop | grep develop >/dev/null 2>&1; then
           if ! git pull origin develop --rebase; then
             echo "Error: Não foi possível atualizar a branch 'develop' com a remota."
             exit 1
           fi
+        else
+          echo "A branch 'develop' não existe no repositório remoto. Pulando o pull."
         fi
 
     rebase-current-branch:
@@ -56,18 +60,31 @@ pre-push:
           exit 1
         fi
 
-        if ! git rebase develop; then
-          echo "Error: O rebase da branch 'develop' na branch '${current_branch}' falhou. Por favor, resolva os conflitos de merge e continue o rebase."
-          exit 1
+        # Apenas rebase se não estiver na branch 'develop'
+        if [ "$current_branch" != "develop" ]; then
+          if ! git rebase develop; then
+            echo "Error: O rebase da branch 'develop' na branch '${current_branch}' falhou. Por favor, resolva os conflitos de merge e continue o rebase."
+            exit 1
+          fi
+        else
+          echo "A branch atual está em 'develop'. Pulando rebase."
         fi
 
     push-current-branch:
       run: |
-        if ! git push --set-upstream origin $current_branch; then
-          echo "Error: Não foi possível fazer push da branch '${current_branch}' para o repositório remoto."
-          exit 1
+        # Certifica-se de que a branch tenha um upstream configurado antes de fazer push
+        if ! git rev-parse --abbrev-ref --symbolic-full-name @{u} >/dev/null 2>&1; then
+          echo "A branch '${current_branch}' não tem um upstream configurado. Configurando upstream..."
+          if ! git push --set-upstream origin $current_branch; then
+            echo "Error: Não foi possível fazer push da branch '${current_branch}' para o repositório remoto."
+            exit 1
+          fi
+        else
+          if ! git push; then
+            echo "Error: Não foi possível fazer push da branch '${current_branch}' para o repositório remoto."
+            exit 1
+          fi
         fi
-
 pre-commit:
   parallel: true
   commands:
